# Generated by Django 5.0.4 on 2024-04-14 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
