# Generated by Django 5.0.4 on 2024-04-14 09:08

import django.core.validators
import eventer_app.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_create_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Festivals', 'Festivals'), ('Conferences', 'Conferences'), ('Performing Art', 'Performing Art'), ('Concerts', 'Concerts'), ('Theme Party', 'Theme Party'), ('Other', 'Other')])),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(validators=[eventer_app.web.validators.validate_not_in_past])),
                ('event_image', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=20, validators=[eventer_app.web.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5), eventer_app.web.validators.validate_at_least_one_digit]),
        ),
    ]
