# Generated by Django 5.0.4 on 2024-04-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_event_alter_profilemodel_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileModel',
            new_name='Profile',
        ),
    ]
