# Generated by Django 5.0.2 on 2024-02-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_project_employee_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(related_name='employees', to='web.project'),
        ),
    ]
