# Generated by Django 5.0.4 on 2024-04-15 15:23

import car_collection_app.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
