# Generated by Django 5.0.4 on 2024-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tite',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
