# Generated by Django 5.0.4 on 2024-04-17 09:20

import django.core.validators
import tasty_recipes_app.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), tasty_recipes_app.web.validators.validate_string_at_least_2_char]),
        ),
    ]
