# Generated by Django 5.0.2 on 2024-02-26 20:02

import models_demo.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(validators=[models_demo.web.validators.validate_in_the_past]),
        ),
    ]
