# Generated by Django 5.0.2 on 2024-02-29 19:31

import forms_part_2_demo.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25, validators=[forms_part_2_demo.web.validators.validate_text])),
                ('priority', models.IntegerField(validators=[forms_part_2_demo.web.validators.ValueInRangeValidator])),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
